<?php

return [
    /*
    |--------------------------------------------------------------------------
    | COBIT GAMO Mapping & Evolution Matrix
    |--------------------------------------------------------------------------
    |
    | Pemetaan komprehensif evolusi Governance and Management Objectives (GAMO)
    | dari COBIT 4.1 (2007) -> COBIT 5 (2012) -> COBIT 2019 (2019).
    |
    */

    'domains' => [
        'EDM' => [
            'name' => 'Evaluate, Direct and Monitor',
            'type' => 'Governance',
            'color' => '#0f2b5c',
            'badge_class' => 'bg-navy',
            'count' => 5,
            'desc' => 'Domain Tata Kelola (Governance) yang berfokus pada evaluasi kebutuhan pemangku kepentingan, arahan strategis, dan pengawasan kinerja.',
        ],
        'APO' => [
            'name' => 'Align, Plan and Organize',
            'type' => 'Management',
            'color' => '#0284c7',
            'badge_class' => 'bg-sky',
            'count' => 14,
            'desc' => 'Domain Manajemen yang mencakup keseluruhan strategi, arsitektur, inovasi, portofolio, risiko, dan keamanan I&T.',
        ],
        'BAI' => [
            'name' => 'Build, Acquire and Implement',
            'type' => 'Management',
            'color' => '#d97706',
            'badge_class' => 'bg-amber',
            'count' => 11,
            'desc' => 'Domain Manajemen yang mencakup identifikasi kebutuhan, pengadaan, pengembangan, dan penerapan solusi serta perubahan I&T.',
        ],
        'DSS' => [
            'name' => 'Deliver, Service and Support',
            'type' => 'Management',
            'color' => '#059669',
            'badge_class' => 'bg-emerald',
            'count' => 6,
            'desc' => 'Domain Manajemen yang menangani operasional harian sistem I&T, manajemen insiden, kontinuitas layanan, dan keamanan operasional.',
        ],
        'MEA' => [
            'name' => 'Monitor, Evaluate and Assess',
            'type' => 'Management',
            'color' => '#dc2626',
            'badge_class' => 'bg-rose',
            'count' => 4,
            'desc' => 'Domain Manajemen yang berfokus pada pengawasan kinerja internal, evaluasi sistem pengendalian, kepatuhan regulasi, dan penjaminan independen.',
        ],
    ],

    'gamo' => [
        // ==========================================
        // EDM - Evaluate, Direct and Monitor
        // ==========================================
        'EDM01' => [
            'id' => 'EDM01',
            'domain' => 'EDM',
            'title_2019' => 'Evaluated, Directed and Monitored Governance Framework Setting and Maintenance',
            'desc_2019' => 'Menganalisis dan mengartikulasikan persyaratan untuk tata kelola I&T enterprise, menetapkan serta memelihara struktur, proses, dan praktik tata kelola yang transparan dan dapat diandalkan.',
            'cobit5_id' => 'EDM01',
            'cobit5_title' => 'Ensure Governance Framework Setting and Maintenance',
            'cobit4_id' => '-',
            'cobit4_title' => '-',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Domain Tata Kelola (EDM) belum ada di COBIT 4.1. Tata kelola terpisah baru diperkenalkan di COBIT 5 dan disempurnakan di COBIT 2019 dengan panduan Design Factors.',
        ],
        'EDM02' => [
            'id' => 'EDM02',
            'domain' => 'EDM',
            'title_2019' => 'Evaluated, Directed and Monitored Benefits Delivery',
            'desc_2019' => 'Mengoptimalkan kontribusi nilai terhadap bisnis dari proses bisnis, layanan I&T, dan aset I&T yang dihasilkan dari pengeluaran investasi I&T dengan biaya yang dapat diterima.',
            'cobit5_id' => 'EDM02',
            'cobit5_title' => 'Ensure Benefits Delivery',
            'cobit4_id' => '-',
            'cobit4_title' => '-',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Domain Tata Kelola (EDM) belum ada di COBIT 4.1. Tata kelola realisasi manfaat diadopsi dari Val IT ke COBIT 5 (EDM02) lalu berlanjut ke COBIT 2019.',
        ],
        'EDM03' => [
            'id' => 'EDM03',
            'domain' => 'EDM',
            'title_2019' => 'Evaluated, Directed and Monitored Risk Optimization',
            'desc_2019' => 'Memastikan bahwa selera risiko (risk appetite) dan toleransi risiko perusahaan dipahami, diartikulasikan, dan dikomunikasikan secara konsisten di seluruh enterprise.',
            'cobit5_id' => 'EDM03',
            'cobit5_title' => 'Ensure Risk Optimization',
            'cobit4_id' => '-',
            'cobit4_title' => '-',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Domain Tata Kelola (EDM) belum ada di COBIT 4.1. Diperkenalkan di COBIT 5 (dari integrasi Risk IT) dan diperkuat pengawasannya di COBIT 2019.',
        ],
        'EDM04' => [
            'id' => 'EDM04',
            'domain' => 'EDM',
            'title_2019' => 'Evaluated, Directed and Monitored Resource Optimization',
            'desc_2019' => 'Memastikan bahwa kapabilitas sumber daya (manusia, finansial, informasi, infrastruktur) I&T perusahaan terpenuhi secara optimal untuk mendukung sasaran strategis bisnis.',
            'cobit5_id' => 'EDM04',
            'cobit5_title' => 'Ensure Resource Optimization',
            'cobit4_id' => '-',
            'cobit4_title' => '-',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Domain Tata Kelola (EDM) belum ada di COBIT 4.1. Tata kelola optimasi sumber daya diperkenalkan di COBIT 5 dan berevolusi ke COBIT 2019.',
        ],
        'EDM05' => [
            'id' => 'EDM05',
            'domain' => 'EDM',
            'title_2019' => 'Evaluated, Directed and Monitored Stakeholder Engagement',
            'desc_2019' => 'Memastikan kinerja dan kepatuhan sistem tata kelola I&T dikomunikasikan secara efektif kepada pemangku kepentingan internal dan eksternal secara transparan.',
            'cobit5_id' => 'EDM05',
            'cobit5_title' => 'Ensure Stakeholder Transparency',
            'cobit4_id' => '-',
            'cobit4_title' => '-',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Domain Tata Kelola (EDM) belum ada di COBIT 4.1. Ditransformasikan dari EDM05 COBIT 5 (Transparency -> Stakeholder Engagement).',
        ],

        // ==========================================
        // APO - Align, Plan and Organize
        // ==========================================
        'APO01' => [
            'id' => 'APO01',
            'domain' => 'APO',
            'title_2019' => 'Managed I&T Management Framework',
            'desc_2019' => 'Merancang sistem manajemen terintegrasi untuk I&T enterprise berdasarkan enterprise goals dan design factors, serta menerapkan seluruh komponen tata kelola yang diperlukan.',
            'cobit5_id' => 'APO01',
            'cobit5_title' => 'Manage the IT Management Framework',
            'cobit4_id' => 'PO4',
            'cobit4_title' => 'PO4 Define the IT Processes, Organisation and Relationships',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Perubahan terminologi dari "IT" menjadi "I&T" (Information and Technology). Menetapkan fondasi struktur manajemen, wewenang, dan kepemilikan 7 komponen COBIT.',
        ],
        'APO02' => [
            'id' => 'APO02',
            'domain' => 'APO',
            'title_2019' => 'Managed Strategy',
            'desc_2019' => 'Mendukung strategi enterprise dengan merumuskan strategi I&T yang selaras, menerjemahkan arah strategis ke dalam rencana taktis dan inisiatif digital.',
            'cobit5_id' => 'APO02',
            'cobit5_title' => 'Manage Strategy',
            'cobit4_id' => 'PO1, PO2',
            'cobit4_title' => 'PO1 Define a Strategic IT Plan & PO2 Define Information Architecture',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Peningkatan fokus pada strategi transformasi digital, roadmap kapabilitas I&T jangka panjang, dan integrasi dengan model bisnis perusahaan.',
        ],
        'APO03' => [
            'id' => 'APO03',
            'domain' => 'APO',
            'title_2019' => 'Managed Enterprise Architecture',
            'desc_2019' => 'Membangun arsitektur enterprise yang konsisten yang mencakup lapisan proses bisnis, informasi/data, aplikasi, dan teknologi.',
            'cobit5_id' => 'APO03',
            'cobit5_title' => 'Manage Enterprise Architecture',
            'cobit4_id' => 'PO2, PO3',
            'cobit4_title' => 'PO2 Define Information Architecture & PO3 Determine Technological Direction',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penyelarasan dengan framework modern seperti TOGAF. Penekanan pada interoperabilitas, standar arsitektur microservices, API, dan multi-cloud.',
        ],
        'APO04' => [
            'id' => 'APO04',
            'domain' => 'APO',
            'title_2019' => 'Managed Innovation',
            'desc_2019' => 'Menjaga kesadaran akan perkembangan I&T terbaru dan tren teknologi yang berpotensi memberikan keunggulan kompetitif bagi bisnis.',
            'cobit5_id' => 'APO04',
            'cobit5_title' => 'Manage Innovation',
            'cobit4_id' => 'PO3',
            'cobit4_title' => 'PO3 Determine Technological Direction',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Menekankan kultur inovasi berkelanjutan, eksperimen terukur, Proof of Concept (PoC) berbasis kecerdasan buatan, otomasi, dan analitik canggih.',
        ],
        'APO05' => [
            'id' => 'APO05',
            'domain' => 'APO',
            'title_2019' => 'Managed Portfolio',
            'desc_2019' => 'Mengoptimalkan kinerja keseluruhan portofolio program, proyek, dan layanan I&T yang selaras dengan sasaran strategis bisnis.',
            'cobit5_id' => 'APO05',
            'cobit5_title' => 'Manage Portfolio',
            'cobit4_id' => 'PO5, PO6',
            'cobit4_title' => 'PO5 Manage IT Investment & PO6 Communicate Aims and Direction',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Evolusi portofolio manajemen berbasis nilai (Val IT) dengan prioritisasi inisiatif I&T dinamis dan alokasi modal berbasis return.',
        ],
        'APO06' => [
            'id' => 'APO06',
            'domain' => 'APO',
            'title_2019' => 'Managed Budget and Costs',
            'desc_2019' => 'Mengelola keuangan dan akuntansi I&T secara transparan dan akuntabel, memastikan alokasi anggaran mencerminkan prioritas bisnis.',
            'cobit5_id' => 'APO06',
            'cobit5_title' => 'Manage Budgets and Costs',
            'cobit4_id' => 'PO5',
            'cobit4_title' => 'PO5 Manage IT Investment',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penyesuaian metode pembiayaan untuk mengakomodasi model langganan cloud (OpEx) versus belanja modal aset fisik konvensional (CapEx).',
        ],
        'APO07' => [
            'id' => 'APO07',
            'domain' => 'APO',
            'title_2019' => 'Managed Human Resources',
            'desc_2019' => 'Menyediakan dan memelihara tenaga kerja I&T yang kompeten, termotivasi, dan selaras dengan kebutuhan organisasi saat ini dan masa depan.',
            'cobit5_id' => 'APO07',
            'cobit5_title' => 'Manage Human Resources',
            'cobit4_id' => 'PO7',
            'cobit4_title' => 'PO7 Manage IT Human Resources',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Fokus pada digital skills framework (seperti SFIA), rekrutmen talenta teknologi baru, suksesi talenta kunci, dan agile squad allocation.',
        ],
        'APO08' => [
            'id' => 'APO08',
            'domain' => 'APO',
            'title_2019' => 'Managed Relationships',
            'desc_2019' => 'Menciptakan dan memelihara hubungan kolaboratif dan terpercaya antara fungsi I&T dan unit bisnis organisasi.',
            'cobit5_id' => 'APO08',
            'cobit5_title' => 'Manage Relationships',
            'cobit4_id' => 'PO6',
            'cobit4_title' => 'PO6 Communicate Aims and Direction',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penguatan peran Business Relationship Management (BRM) untuk menghubungkan kebutuhan bisnis dengan kapabilitas teknologi secara berkelanjutan.',
        ],
        'APO09' => [
            'id' => 'APO09',
            'domain' => 'APO',
            'title_2019' => 'Managed Service Agreements',
            'desc_2019' => 'Menyelaraskan layanan I&T yang diberikan dengan kebutuhan bisnis melalui penetapan katalog layanan dan Service Level Agreements (SLA).',
            'cobit5_id' => 'APO09',
            'cobit5_title' => 'Manage Service Agreements',
            'cobit4_id' => 'DS1, DS2',
            'cobit4_title' => 'DS1 Define and Manage Service Levels & DS2 Manage Third-Party Services',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Peningkatan pengelolaan SLA, OLA, dan Underpinning Contracts (UC) di lingkungan multi-provider dan Software-as-a-Service (SaaS).',
        ],
        'APO10' => [
            'id' => 'APO10',
            'domain' => 'APO',
            'title_2019' => 'Managed Vendors',
            'desc_2019' => 'Mengelola hubungan, kontrak, dan kinerja vendor eksternal untuk memastikan penyediaan produk dan layanan I&T yang optimal.',
            'cobit5_id' => 'APO10',
            'cobit5_title' => 'Manage Suppliers',
            'cobit4_id' => 'AI5, DS2',
            'cobit4_title' => 'AI5 Procure IT Resources & DS2 Manage Third-Party Services',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Perubahan nama dari "Suppliers" menjadi "Vendors". Penguatan manajemen risiko rantai pasok (supply chain risk) dan tata kelola ekosistem vendor digital.',
        ],
        'APO11' => [
            'id' => 'APO11',
            'domain' => 'APO',
            'title_2019' => 'Managed Quality',
            'desc_2019' => 'Mendefinisikan dan menerapkan standar mutu untuk semua proses, produk, dan layanan I&T secara berkesinambungan.',
            'cobit5_id' => 'APO11',
            'cobit5_title' => 'Manage Quality',
            'cobit4_id' => 'PO8',
            'cobit4_title' => 'PO8 Manage Quality',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Integrasi metodologi Continuous Quality Improvement (CQI), jaminan mutu pada pipeline CI/CD, dan audit kepuasan pelanggan.',
        ],
        'APO12' => [
            'id' => 'APO12',
            'domain' => 'APO',
            'title_2019' => 'Managed Risk',
            'desc_2019' => 'Mengidentifikasi, menilai, dan memitigasi risiko terkait I&T secara berkala dalam batas toleransi risiko yang telah ditetapkan oleh dewan tata kelola.',
            'cobit5_id' => 'APO12',
            'cobit5_title' => 'Manage Risk',
            'cobit4_id' => 'PO9',
            'cobit4_title' => 'PO9 Assess and Manage IT Risks',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Pemeliharaan risk profile dan risk register terpadu, integrasi ke Enterprise Risk Management (ERM), serta skenario ancaman siber terdepan.',
        ],
        'APO13' => [
            'id' => 'APO13',
            'domain' => 'APO',
            'title_2019' => 'Managed Security',
            'desc_2019' => 'Mendefinisikan, mengoperasikan, dan memantau sistem manajemen keamanan informasi (ISMS) untuk melindungi kerahasiaan, integritas, dan ketersediaan aset informasi.',
            'cobit5_id' => 'APO13',
            'cobit5_title' => 'Manage Security',
            'cobit4_id' => 'DS5',
            'cobit4_title' => 'DS5 Ensure Systems Security',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penyelarasan komprehensif dengan standar internasional ISO/IEC 27001 dan NIST Cybersecurity Framework.',
        ],
        'APO14' => [
            'id' => 'APO14',
            'domain' => 'APO',
            'title_2019' => 'Managed Data',
            'desc_2019' => 'Memastikan bahwa data enterprise dikelola sebagai aset bernilai strategis, menjamin kualitas, keamanan, privasi, kepatuhan, dan ketersediaan data.',
            'cobit5_id' => 'Belum ada',
            'cobit5_title' => 'Tidak tersedia di COBIT 5 (tersebar parsial di DSS06)',
            'cobit4_id' => 'DS11 (parsial)',
            'cobit4_title' => 'DS11 Manage Data',
            'status' => 'new',
            'status_label' => 'OBJEKTIF BARU DI COBIT 2019',
            'notes' => '★ OBJEKTIF BARU! Ditambahkan khusus di COBIT 2019 untuk menjawab ledakan data (Big Data), perlindungan privasi data pribadi (GDPR/UU PDP), arsitektur data master, dan integritas siklus hidup data.',
        ],

        // ==========================================
        // BAI - Build, Acquire and Implement
        // ==========================================
        'BAI01' => [
            'id' => 'BAI01',
            'domain' => 'BAI',
            'title_2019' => 'Managed Programs',
            'desc_2019' => 'Mengelola program investasi I&T secara menyeluruh, mengoordinasikan paket proyek yang saling terkait untuk memastikan realisasi manfaat bisnis.',
            'cobit5_id' => 'BAI01 (parsial)',
            'cobit5_title' => 'Manage Programmes and Projects',
            'cobit4_id' => 'PO10',
            'cobit4_title' => 'PO10 Manage Projects',
            'status' => 'restructured',
            'status_label' => 'Restrukturisasi / Pemisahan',
            'notes' => '★ RESTRUKTURISASI. Pada COBIT 5, program dan proyek digabung dalam BAI01. Di COBIT 2019, BAI01 dikhususkan murni untuk PROGRAM (kumpulan proyek), sedangkan proyek individual dipisah ke BAI11.',
        ],
        'BAI02' => [
            'id' => 'BAI02',
            'domain' => 'BAI',
            'title_2019' => 'Managed Requirements Definition',
            'desc_2019' => 'Mengidentifikasi dan mendokumentasikan kebutuhan bisnis dan teknis secara jelas, serta memvalidasi kesesuaian solusi digital dengan kebutuhan organisasi.',
            'cobit5_id' => 'BAI02',
            'cobit5_title' => 'Manage Requirements Definition',
            'cobit4_id' => 'AI1',
            'cobit4_title' => 'AI1 Identify Automated Solutions',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Peningkatan pendekatan agile user story gathering, integrasi kebutuhan kepatuhan hukum sejak tahap perancangan (compliance by design).',
        ],
        'BAI03' => [
            'id' => 'BAI03',
            'domain' => 'BAI',
            'title_2019' => 'Managed Solutions Identification and Build',
            'desc_2019' => 'Membangun atau mengadakan solusi I&T yang tepat guna sesuai kebutuhan bisnis, mencakup perangkat lunak, infrastruktur, dan integrasi sistem.',
            'cobit5_id' => 'BAI03',
            'cobit5_title' => 'Manage Solutions Identification and Build',
            'cobit4_id' => 'AI2, AI3',
            'cobit4_title' => 'AI2 Acquire and Maintain Application Software & AI3 Acquire/Maintain Infrastructure',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Mendukung praktik pengembangan perangkat lunak modern: Agile, DevOps, kontainerisasi (Docker/Kubernetes), dan integrasi API.',
        ],
        'BAI04' => [
            'id' => 'BAI04',
            'domain' => 'BAI',
            'title_2019' => 'Managed Availability and Capacity',
            'desc_2019' => 'Mengimbangi kebutuhan ketersediaan dan kapasitas layanan I&T terhadap biaya dan sumber daya yang tersedia untuk memenuhi ekspektasi performa.',
            'cobit5_id' => 'BAI04',
            'cobit5_title' => 'Manage Availability and Capacity',
            'cobit4_id' => 'DS3',
            'cobit4_title' => 'DS3 Manage Performance and Capacity',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Pengelolaan kapasitas elastis dan ketersediaan tinggi di arsitektur cloud, pemantauan utilisasi otomatis, dan predictive capacity planning.',
        ],
        'BAI05' => [
            'id' => 'BAI05',
            'domain' => 'BAI',
            'title_2019' => 'Managed Organizational Change',
            'desc_2019' => 'Mempersiapkan dan mengelola pemangku kepentingan organisasi agar siap mengadopsi perubahan proses bisnis dan sistem teknologi baru.',
            'cobit5_id' => 'BAI05',
            'cobit5_title' => 'Manage Organisational Change Enablement',
            'cobit4_id' => 'AI4',
            'cobit4_title' => 'AI4 Enable Operation and Use',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penyesuaian nama menjadi "Managed Organizational Change". Mengedepankan sisi manusia (people side) dalam transformasi digital, komunikasi perubahan, dan literasi teknologi.',
        ],
        'BAI06' => [
            'id' => 'BAI06',
            'domain' => 'BAI',
            'title_2019' => 'Managed IT Changes',
            'desc_2019' => 'Mengendalikan seluruh perubahan pada sistem I&T secara terencana dan terstruktur untuk meminimalkan dampak gangguan operasional pada bisnis.',
            'cobit5_id' => 'BAI06',
            'cobit5_title' => 'Manage Changes',
            'cobit4_id' => 'AI6',
            'cobit4_title' => 'AI6 Manage Changes',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Perubahan nama menjadi "Managed IT Changes" untuk memperjelas batas antara perubahan teknis TI dan perubahan organisasi (BAI05). Mendukung change approval board (CAB) dan otomatisasi deploy.',
        ],
        'BAI07' => [
            'id' => 'BAI07',
            'domain' => 'BAI',
            'title_2019' => 'Managed IT Change Acceptance and Transition',
            'desc_2019' => 'Menguji dan mengesahkan solusi sistem baru atau perubahan sistem sebelum diterapkan ke lingkungan produksi operasional bisnis.',
            'cobit5_id' => 'BAI07',
            'cobit5_title' => 'Manage Change Acceptance and Transition',
            'cobit4_id' => 'AI7',
            'cobit4_title' => 'AI7 Install and Accredit Solutions and Changes',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penyesuaian nama dengan penambahan "IT". Memperkuat pengujian terotomasi, UAT, staging deployment, dan rencana rollback saat transisi rilis.',
        ],
        'BAI08' => [
            'id' => 'BAI08',
            'domain' => 'BAI',
            'title_2019' => 'Managed Knowledge',
            'desc_2019' => 'Memelihara ketersediaan pengetahuan, informasi operasional, dan dokumentasi yang relevan untuk mendukung seluruh aktivitas I&T.',
            'cobit5_id' => 'BAI08',
            'cobit5_title' => 'Manage Knowledge',
            'cobit4_id' => 'DS7 (parsial)',
            'cobit4_title' => 'DS7 Educate and Train Users',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Peningkatan knowledge sharing, retensi aset pengetahuan saat pergantian personel, dan platform basis pengetahuan digital yang mudah diakses.',
        ],
        'BAI09' => [
            'id' => 'BAI09',
            'domain' => 'BAI',
            'title_2019' => 'Managed Assets',
            'desc_2019' => 'Mengelola aset I&T di seluruh siklus hidupnya untuk memastikan nilai penggunaan aset maksimal dan kepatuhan terhadap lisensi.',
            'cobit5_id' => 'BAI09',
            'cobit5_title' => 'Manage Assets',
            'cobit4_id' => 'AI5, DS9',
            'cobit4_title' => 'AI5 Procure IT Resources & DS9 Manage Configuration',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Mencakup Hardware Asset Management (HAM), Software Asset Management (SAM), serta cloud asset tagging dan optimasi biaya lisensi.',
        ],
        'BAI10' => [
            'id' => 'BAI10',
            'domain' => 'BAI',
            'title_2019' => 'Managed Configuration',
            'desc_2019' => 'Mendefinisikan dan memelihara informasi tentang seluruh item konfigurasi (CI) dan keterhubungannya dalam Configuration Management Database (CMDB).',
            'cobit5_id' => 'BAI10',
            'cobit5_title' => 'Manage Configuration',
            'cobit4_id' => 'DS9',
            'cobit4_title' => 'DS9 Manage Configuration',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Mendukung arsitektur Infrastructure as Code (IaC), audit baseline konfigurasi, dan otomatisasi verifikasi konfigurasi sistem.',
        ],
        'BAI11' => [
            'id' => 'BAI11',
            'domain' => 'BAI',
            'title_2019' => 'Managed Projects',
            'desc_2019' => 'Mengelola setiap proyek I&T secara terdefinisi dan konsisten, mencakup perencanaan lingkup, jadwal, biaya, risiko, dan penyampaian hasil proyek.',
            'cobit5_id' => 'Dipisah dari BAI01',
            'cobit5_title' => 'Dipisahkan dari COBIT 5 BAI01 (Manage Programmes and Projects)',
            'cobit4_id' => 'PO10',
            'cobit4_title' => 'PO10 Manage Projects',
            'status' => 'new',
            'status_label' => 'OBJEKTIF DEDIKASI BARU DI COBIT 2019',
            'notes' => '★ OBJEKTIF DEDIKASI BARU! Dipisahkan dari manajemen program (BAI01) untuk memberikan pedoman terperinci khusus bagi tata kelola eksekusi proyek I&T, baik dengan pendekatan waterfall maupun agile sprint.',
        ],

        // ==========================================
        // DSS - Deliver, Service and Support
        // ==========================================
        'DSS01' => [
            'id' => 'DSS01',
            'domain' => 'DSS',
            'title_2019' => 'Managed Operations',
            'desc_2019' => 'Menjalankan prosedur operasional I&T sehari-hari secara konsisten dan andal untuk memastikan kestabilan pengiriman layanan bagi bisnis.',
            'cobit5_id' => 'DSS01',
            'cobit5_title' => 'Manage Operations',
            'cobit4_id' => 'DS13, DS12',
            'cobit4_title' => 'DS13 Manage Operations & DS12 Manage Physical Environment',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Peningkatan otomatisasi pemantauan operasional, job scheduling, manajemen backup & restore, dan pengelolaan lingkungan fasilitas data center/cloud.',
        ],
        'DSS02' => [
            'id' => 'DSS02',
            'domain' => 'DSS',
            'title_2019' => 'Managed Service Requests and Incidents',
            'desc_2019' => 'Memberikan respons tepat waktu terhadap permintaan layanan dan insiden I&T untuk meminimalkan dampak terhadap produktivitas bisnis.',
            'cobit5_id' => 'DSS02',
            'cobit5_title' => 'Manage Service Requests and Incidents',
            'cobit4_id' => 'DS8',
            'cobit4_title' => 'DS8 Manage Service Desk and Incidents',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Modernisasi IT Service Desk, otomatisasi tiket layanan (ticketing workflow), eskalasi insiden kritis, dan komunikasi status insiden.',
        ],
        'DSS03' => [
            'id' => 'DSS03',
            'domain' => 'DSS',
            'title_2019' => 'Managed Problems',
            'desc_2019' => 'Mengidentifikasi akar penyebab (root cause) insiden, mencatat solusi sementara (workaround), dan mencegah insiden serupa terulang kembali.',
            'cobit5_id' => 'DSS03',
            'cobit5_title' => 'Manage Problems',
            'cobit4_id' => 'DS10',
            'cobit4_title' => 'DS10 Manage Problems',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Pengelolaan Known Error Database (KEDB), analisis proaktif pola insiden, dan integrasi penanganan problem dengan proses change management.',
        ],
        'DSS04' => [
            'id' => 'DSS04',
            'domain' => 'DSS',
            'title_2019' => 'Managed Continuity',
            'desc_2019' => 'Menetapkan dan menguji kapabilitas ketahanan dan pemulihan sistem I&T (Disaster Recovery) untuk memastikan kontinuitas operasi bisnis.',
            'cobit5_id' => 'DSS04',
            'cobit5_title' => 'Manage Continuity',
            'cobit4_id' => 'DS4',
            'cobit4_title' => 'DS4 Ensure Continuous Service',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penyelarasan dengan ISO 22301, pengujian rutin RTO (Recovery Time Objective) dan RPO (Recovery Point Objective), serta strategi ketahanan cloud multi-region.',
        ],
        'DSS05' => [
            'id' => 'DSS05',
            'domain' => 'DSS',
            'title_2019' => 'Managed Security Services',
            'desc_2019' => 'Mengoperasikan kontrol keamanan teknis untuk melindungi aset I&T enterprise dari ancaman siber, malware, dan akses yang tidak sah.',
            'cobit5_id' => 'DSS05',
            'cobit5_title' => 'Manage Security Services',
            'cobit4_id' => 'DS5',
            'cobit4_title' => 'DS5 Ensure Systems Security',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penguatan Security Operations Center (SOC), endpoint protection, manajemen kerentanan (vulnerability assessment), dan identity & access management (IAM).',
        ],
        'DSS06' => [
            'id' => 'DSS06',
            'domain' => 'DSS',
            'title_2019' => 'Managed Business Process Controls',
            'desc_2019' => 'Menerapkan dan memelihara pengendalian aplikasi terotomasi dalam proses bisnis untuk menjaga integritas dan keabsahan transaksi informasi.',
            'cobit5_id' => 'DSS06',
            'cobit5_title' => 'Manage Business Process Controls',
            'cobit4_id' => 'DS11, AC1-AC6',
            'cobit4_title' => 'DS11 Manage Data & AC1-AC6 Application Controls',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Mencakup automated input authorization, data processing validation, audit trail transaksi, serta pemisahan tugas (segregation of duties/SoD).',
        ],

        // ==========================================
        // MEA - Monitor, Evaluate and Assess
        // ==========================================
        'MEA01' => [
            'id' => 'MEA01',
            'domain' => 'MEA',
            'title_2019' => 'Managed Performance and Conformance Monitoring',
            'desc_2019' => 'Mengumpulkan, memvalidasi, dan mengevaluasi data metrik proses I&T untuk memastikan kesesuaian target kinerja dan rencana bisnis.',
            'cobit5_id' => 'MEA01',
            'cobit5_title' => 'Monitor, Evaluate and Assess Performance and Conformance',
            'cobit4_id' => 'ME1',
            'cobit4_title' => 'ME1 Monitor and Evaluate IT Performance',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penyesuaian penamaan proses. Pemanfaatan dashboard real-time, Balanced Scorecard I&T, dan pelaporan metrik kinerja berkala kepada dewan eksekutif.',
        ],
        'MEA02' => [
            'id' => 'MEA02',
            'domain' => 'MEA',
            'title_2019' => 'Managed System of Internal Control',
            'desc_2019' => 'Secara berkesinambungan memantau dan mengevaluasi efektivitas lingkungan pengendalian internal I&T enterprise.',
            'cobit5_id' => 'MEA02',
            'cobit5_title' => 'Monitor, Evaluate and Assess the System of Internal Control',
            'cobit4_id' => 'ME2',
            'cobit4_title' => 'ME2 Monitor and Evaluate Internal Control',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penyesuaian nama proses. Penekanan pada evaluasi mandiri kontrol (Control Self-Assessment/CSA) dan tindak lanjut perbaikan temuan defisiensi kontrol internal.',
        ],
        'MEA03' => [
            'id' => 'MEA03',
            'domain' => 'MEA',
            'title_2019' => 'Managed Compliance With External Requirements',
            'desc_2019' => 'Mengevaluasi dan memastikan bahwa proses I&T dan solusi teknologi senantiasa mematuhi semua hukum, regulasi, dan kewajiban kontrak eksternal.',
            'cobit5_id' => 'MEA03',
            'cobit5_title' => 'Monitor, Evaluate and Assess Compliance with External Requirements',
            'cobit4_id' => 'ME3',
            'cobit4_title' => 'ME3 Ensure Regulatory Compliance',
            'status' => 'evolved',
            'status_label' => 'Evolusi dari COBIT 5',
            'notes' => 'Penyesuaian nama proses. Pemantauan proaktif regulasi perlindungan data pribadi (UU PDP/GDPR), regulasi sektor industri (perbankan/finansial), dan standar hukum.',
        ],
        'MEA04' => [
            'id' => 'MEA04',
            'domain' => 'MEA',
            'title_2019' => 'Managed Assurance',
            'desc_2019' => 'Merencanakan, memfasilitasi, dan melaksanakan inisiatif penjaminan (assurance) I&T independen untuk memberikan keyakinan memadai bagi dewan dan regulator.',
            'cobit5_id' => 'Belum ada',
            'cobit5_title' => 'Tidak tersedia di COBIT 5 (tersebar parsial di MEA02)',
            'cobit4_id' => 'ME2 (parsial), ME4',
            'cobit4_title' => 'ME2 Monitor Internal Control & ME4 Provide IT Governance',
            'status' => 'new',
            'status_label' => 'OBJEKTIF BARU DI COBIT 2019',
            'notes' => '★ OBJEKTIF BARU! Ditambahkan khusus di COBIT 2019 untuk mengelola fungsi audit independen I&T, penetapan ruang lingkup penjaminan (assurance scope), evaluasi bukti, dan pelaporan independen.',
        ],
    ],
];
